#!/usr/bin/env bash

function home_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile cljs "$shome/server.cljs" "$shome/server"

  "$shome/script/update"
}

home_update "$@"
