#!/usr/bin/env bash

function home_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$shome/server" ]]; then
    return 0
  fi

  return 1
}

home_update "$@"
