#!/usr/bin/env bash

function home_update {
  local shome="${_apt_mirror_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  install -dv -m 0755 "$BASEBOX_CACHE/cache/apt-mirror"
  install -dv -m 0755 "$BASEBOX_CACHE/cache/apt-mirror/var"

  ln -nfs "$shome/script/rewrite-apt.pl" "$BASEBOX_CACHE/cache/apt-mirror/"
  ln -nfs "$shome/script/postmirror.sh" "$BASEBOX_CACHE/cache/apt-mirror/var/"
  touch "$shome/script/clean.sh"
  ln -nfs "$shome/script/clean.sh" "$BASEBOX_CACHE/cache/apt-mirror/var/"

  npm install

  block compile service
}

home_update "$@"
