#!/usr/bin/env bash

function home_update {
  local shome="${_apt_mirror_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  install -dv -m 0755 "$BASEBOX_CACHE/cache/apt-mirror"
  install -dv -m 0755 "$BASEBOX_CACHE/cache/apt-mirror/var"

  touch "$shome/script/clean.sh"

  if [[ "$#" -gt 0 ]]; then
    local pth_mirror="$1"; shift
    ln -nfs "$shome/script/clean.sh" "$pth_mirror/var/"
    ln -nfs "$shome/script/postmirror.sh" "$pth_mirror/var/"
    ln -nfs "$shome/script/rewrite-apt.pl" "$pth_mirror/"
  fi

  npm install

  block compile service
}

home_update "$@"
