#!/usr/bin/env bash

function home_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "$BASEBOX_CACHE/cache/apt-mirror/var"

  ln -nfs "$shome/script/rewrite-apt.pl" "$BASEBOX_CACHE/cache/apt-mirror/"
  ln -nfs "$shome/script/postmirror.sh" "$BASEBOX_CACHE/cache/apt-mirror/var/"
  ln -nfs "$shome/script/clean.sh" "$BASEBOX_CACHE/cache/apt-mirror/var/"

  block compile service
}

home_update "$@"
